### ISSUE TITLE
Handle failure in guest registration

### ISSUE THREAD

**Issue by ashfame** [Automattic/chatrix#211]
When a server doesn't have guest account registration enabled, it fails with this error.

![Screenshot 2023-03-24 at 6 32 33 PM](https://user-images.githubusercontent.com/858906/227554264-0ec3c375-e7d5-4f54-a721-23b9fa6c2f54.png)

It should show unknownRoomView with a login button

**Comment by psrpinto** [comment]
I think this issue manifests itself differently according to whether the user has a session open or not, and also depends on if they have "previously-opened" sessions. That explains why there are different error messages.

I think we might need to rework how single-room mode is handled, specifically in what concerns the case where a previous session exists. [In this code](https://github.com/Automattic/chatrix/blob/8f6681b9a26b3fd06d308b0150eb66061dc479bf/frontend/iframe/viewmodels/RootViewModel.ts#L317) `chosenSession` is not defined, so that's surely part of the issue.

Here's all the use cases I could think of (can you think of any others?), and what I think the behaviour should be for each:

- User has a session open
  -> Navigate to room view for configured `roomIdOrAlias`
- User does not have a session open
  - User has exactly one previously-opened session
    -> Navigate to room view for configured `roomIdOrAlias`
  - User has no previously-opened sessions
    - Room is not world-readable
      -> Navigate to Login
    - Room is world-readable
      -> Do guest login
      -> Navigate to room view for configured `roomIdOrAlias`
  - User has many previously-opened sessions
    -> Navigate to session picker

I think we should rework the code to implement this ^, I would be happy to do so.

**Comment by akirk** [comment]
Great. Please proceed on working on this, it's a blocker as we experienced in today's meeting.

**Comment by ashfame** [comment]
@psrpinto Can you elaborate on what you mean with "session open" here, as I don't understand this branching:

```
- User does not have a session open
    - User has exactly one previously-opened session
```

I would add another condition while doing guest login. When its a 403 (meaning guest registrations on server is disabled), we behave as if the room is not world-readable and navigate to login.

**Comment by psrpinto** [comment]
Good catch, I edited my comment to add the condition for when homeserver has guest registration disabled.

> Can you elaborate on what you mean with "session open" 

By "session open" I mean that the user went past the session picker and is "inside" a session, prior to loading chatrix in single-user mode. (Tthe case where they have a single session is a special case of this, where the session picker isn't displayed, but from a code perspective it's the same, they are "inside" the session even if they don't see the session picker).

**Comment by psrpinto** [comment]
In addition, when I say "previously-opened", I mean they see the session picker with previously used sessions, but they aren't "inside" any session.

**Comment by ashfame** [comment]
Gotcha, thanks for explaining! The complete branching makes sense now & I think that covers everything 👍

**Comment by ashfame** [comment]
Related: https://github.com/Automattic/chatrix/issues/209
